import { Panel } from "../common/Panel";
import { SectionHeader } from "../common/SectionHeader";
import type { OutputFrameManifest } from "../../types/uploads";

interface FrameGalleryProps {
  manifest?: OutputFrameManifest;
}

export function FrameGallery({ manifest }: FrameGalleryProps) {
  const frames = manifest
    ? manifest.groups.flatMap((g) =>
        g.frames.map((f) => ({ ...f, groupLabel: g.label }))
      )
    : [];

  return (
    <Panel>
      <SectionHeader
        title="Latest frame manifest"
        subtitle="Sample key frames generated by Module 1 for review"
      />
      <div className="mt-6 grid gap-4 md:grid-cols-3">
        {frames.length === 0 ? (
          <div className="col-span-full rounded-2xl border border-white/10 bg-white/5 px-4 py-6 text-center text-sm text-white/60">
            No frames available. Once an upload completes the manifest preview
            appears here.
          </div>
        ) : (
          frames.map((frame) => (
            <div
              key={frame.id}
              className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/30 p-4"
            >
              <img
                src={frame.url}
                alt={frame.label || frame.id}
                className="h-40 w-full rounded-xl object-cover"
              />
              <div>
                <p className="text-sm font-semibold text-white">
                  {frame.groupLabel} - {frame.label || "Frame"}
                </p>
                <p className="text-xs text-white/60">
                  Captured{" "}
                  {frame.capturedAt
                    ? new Date(frame.capturedAt).toLocaleString()
                    : "Unknown"}
                </p>
              </div>
            </div>
          ))
        )}
      </div>
    </Panel>
  );
}
