import { useState, useMemo } from "react";
import { SlidersHorizontal, ArrowUpDown } from "lucide-react";
import { Panel } from "../common/Panel";
import { SectionHeader } from "../common/SectionHeader";
import type { OutputFrameManifest } from "../../types/uploads";

interface FrameGalleryProps {
  manifest?: OutputFrameManifest;
}

export function FrameGallery({ manifest }: FrameGalleryProps) {
  const [directionFilter, setDirectionFilter] = useState<string>("all");
  const [sortOrder, setSortOrder] = useState<"newest" | "oldest">("newest");

  const groups = manifest?.groups ?? [];
  const isSingleLane = groups.length === 1;
  const allFrames = groups.flatMap((group) => {
    const groupLabel = isSingleLane ? "Traffic flow" : group.label;
    return group.frames.map((frame) => ({ ...frame, groupLabel }));
  });

  const directions = useMemo(() => {
    const dirs = new Set<string>();
    groups.forEach((g) => dirs.add(g.label));
    return Array.from(dirs).sort();
  }, [groups]);

  const frames = useMemo(() => {
    let filtered = allFrames;

    if (directionFilter !== "all") {
      filtered = filtered.filter((f) => f.groupLabel === directionFilter);
    }

    const sorted = [...filtered].sort((a, b) => {
      const aTime = a.capturedAt ? new Date(a.capturedAt).getTime() : 0;
      const bTime = b.capturedAt ? new Date(b.capturedAt).getTime() : 0;
      return sortOrder === "newest" ? bTime - aTime : aTime - bTime;
    });

    return sorted;
  }, [allFrames, directionFilter, sortOrder]);

  const appendQueryParam = (
    url: string,
    key: string,
    value: string | number
  ) => {
    const separator = url.includes("?") ? "&" : "?";
    return `${url}${separator}${key}=${encodeURIComponent(String(value))}`;
  };

  return (
    <Panel>
      <SectionHeader
        title="Latest frame summary"
        subtitle="Sample key frames generated by the camera analysis service for review"
      />

      {/* Filters */}
      {allFrames.length > 0 && (
        <div className="mt-6 flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2">
            <SlidersHorizontal className="h-4 w-4 text-white/40" />
            <select
              value={directionFilter}
              onChange={(e) => setDirectionFilter(e.target.value)}
              className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white focus:border-sky-500/50 focus:outline-none focus:ring-2 focus:ring-sky-500/20"
            >
              <option value="all">All Directions</option>
              {directions.map((dir) => (
                <option key={dir} value={dir}>
                  {dir}
                </option>
              ))}
            </select>
          </div>

          <div className="flex items-center gap-2">
            <ArrowUpDown className="h-4 w-4 text-white/40" />
            <select
              value={sortOrder}
              onChange={(e) =>
                setSortOrder(e.target.value as "newest" | "oldest")
              }
              className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white focus:border-sky-500/50 focus:outline-none focus:ring-2 focus:ring-sky-500/20"
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
            </select>
          </div>

          <div className="text-xs text-white/50">
            Showing {frames.length} of {allFrames.length} frames
          </div>
        </div>
      )}

      <div className="mt-6 grid gap-4 md:grid-cols-3">
        {frames.length === 0 ? (
          <div className="col-span-full rounded-2xl border border-white/10 bg-white/5 px-4 py-6 text-center text-sm text-white/60">
            No frames available. Once an upload completes the preview appears
            here.
          </div>
        ) : (
          frames.map((frame) => (
            <div
              key={frame.id}
              className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-black/30 p-4"
            >
              {(() => {
                const versionToken = frame.capturedAt
                  ? new Date(frame.capturedAt).getTime()
                  : frame.id;
                const srcWithVersion = appendQueryParam(
                  frame.url,
                  "v",
                  versionToken ?? Date.now()
                );
                return (
                  <img
                    src={srcWithVersion}
                    alt={frame.label || frame.id}
                    className="h-40 w-full rounded-xl object-cover"
                  />
                );
              })()}
              <div>
                <p className="text-sm font-semibold text-white">
                  {frame.groupLabel} - {frame.label || "Frame"}
                </p>
                <p className="text-xs text-white/60">
                  Captured{" "}
                  {frame.capturedAt
                    ? new Date(frame.capturedAt).toLocaleString()
                    : "Unknown"}
                </p>
              </div>
            </div>
          ))
        )}
      </div>
    </Panel>
  );
}
